"""Central Google GenAI client wrapper abstraction."""

import logging
from typing import Any, Dict, Optional, Type, TypeVar

from google import genai
from google.genai import types
from pydantic import BaseModel, Field

from config import Settings, get_settings
from core.ai.exceptions import GenAIAuthError, GenAIClientError, GenAIModelError

logger = logging.getLogger(__name__)

T = TypeVar("T", bound=BaseModel)


class AIResponse(BaseModel):
    """Typed application-level AI response abstraction."""

    text: str = Field(default="", description="Text response content generated by the model.")
    model: str = Field(..., description="Model identifier used for generation.")
    finish_reason: Optional[str] = Field(default=None, description="Generation finish reason.")
    usage: Optional[Dict[str, Any]] = Field(
        default=None, description="Token usage statistics if available."
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict, description="Additional model response metadata."
    )


class GenAIClient:
    """Reusable Google GenAI Client abstraction wrapping official google-genai SDK."""

    def __init__(
        self,
        settings: Optional[Settings] = None,
        client: Optional[genai.Client] = None,
    ) -> None:
        """Initialize GenAIClient.

        Args:
            settings: Settings instance. Defaults to get_settings().
            client: Optional pre-configured genai.Client instance (useful for testing/injection).
        """
        self._settings = settings or get_settings()
        self._default_model = self._settings.gemini_model

        if client is not None:
            self._client = client
        else:
            try:
                api_key = self._settings.api_key
                self._client = genai.Client(api_key=api_key)
            except Exception as e:
                logger.error("Failed to initialize GenAI client: %s", str(e))
                raise GenAIAuthError(f"Failed to initialize GenAI client: {e}") from e

    @property
    def default_model(self) -> str:
        """Get default model name."""
        return self._default_model

    def generate_text(
        self,
        prompt: str,
        system_instruction: Optional[str] = None,
        model: Optional[str] = None,
        temperature: Optional[float] = None,
    ) -> AIResponse:
        """Generate text response using Gemini model synchronously.

        Args:
            prompt: User request or prompt text.
            system_instruction: Optional system instruction.
            model: Model override (defaults to configured default model).
            temperature: Sampling temperature.

        Returns:
            AIResponse: Typed AI response.
        """
        selected_model = model or self._default_model
        config = types.GenerateContentConfig()
        if system_instruction:
            config.system_instruction = system_instruction
        if temperature is not None:
            config.temperature = temperature

        try:
            raw_response = self._client.models.generate_content(
                model=selected_model,
                contents=prompt,
                config=config,
            )
            return self._format_response(raw_response, selected_model)
        except Exception as e:
            logger.error("Error during text generation with model %s: %s", selected_model, str(e))
            raise GenAIModelError(f"GenAI generation failed: {e}") from e

    async def generate_text_async(
        self,
        prompt: str,
        system_instruction: Optional[str] = None,
        model: Optional[str] = None,
        temperature: Optional[float] = None,
    ) -> AIResponse:
        """Generate text response using Gemini model asynchronously.

        Args:
            prompt: User request or prompt text.
            system_instruction: Optional system instruction.
            model: Model override (defaults to configured default model).
            temperature: Sampling temperature.

        Returns:
            AIResponse: Typed AI response.
        """
        selected_model = model or self._default_model
        config = types.GenerateContentConfig()
        if system_instruction:
            config.system_instruction = system_instruction
        if temperature is not None:
            config.temperature = temperature

        try:
            raw_response = await self._client.aio.models.generate_content(
                model=selected_model,
                contents=prompt,
                config=config,
            )
            return self._format_response(raw_response, selected_model)
        except Exception as e:
            logger.error(
                "Error during async text generation with model %s: %s", selected_model, str(e)
            )
            raise GenAIModelError(f"Async GenAI generation failed: {e}") from e

    def generate_structured(
        self,
        prompt: str,
        response_schema: Type[T],
        system_instruction: Optional[str] = None,
        model: Optional[str] = None,
        temperature: Optional[float] = None,
    ) -> T:
        """Generate structured response matching a Pydantic model schema synchronously.

        Args:
            prompt: Prompt text.
            response_schema: Pydantic model class for expected output.
            system_instruction: Optional system instruction.
            model: Model override.
            temperature: Sampling temperature.

        Returns:
            T: Parsed instance of response_schema.
        """
        selected_model = model or self._default_model
        config = types.GenerateContentConfig(
            response_mime_type="application/json",
            response_schema=response_schema,
        )
        if system_instruction:
            config.system_instruction = system_instruction
        if temperature is not None:
            config.temperature = temperature

        try:
            raw_response = self._client.models.generate_content(
                model=selected_model,
                contents=prompt,
                config=config,
            )
            if hasattr(raw_response, "parsed") and raw_response.parsed is not None:
                if isinstance(raw_response.parsed, response_schema):
                    return raw_response.parsed
                return response_schema.model_validate(raw_response.parsed)
            if raw_response.text:
                return response_schema.model_validate_json(raw_response.text)
            raise GenAIModelError("Model returned empty text or unparseable structured output.")
        except Exception as e:
            logger.error(
                "Error during structured generation with model %s: %s", selected_model, str(e)
            )
            raise GenAIModelError(f"Structured GenAI generation failed: {e}") from e

    async def generate_structured_async(
        self,
        prompt: str,
        response_schema: Type[T],
        system_instruction: Optional[str] = None,
        model: Optional[str] = None,
        temperature: Optional[float] = None,
    ) -> T:
        """Generate structured response matching a Pydantic model schema asynchronously.

        Args:
            prompt: Prompt text.
            response_schema: Pydantic model class for expected output.
            system_instruction: Optional system instruction.
            model: Model override.
            temperature: Sampling temperature.

        Returns:
            T: Parsed instance of response_schema.
        """
        selected_model = model or self._default_model
        config = types.GenerateContentConfig(
            response_mime_type="application/json",
            response_schema=response_schema,
        )
        if system_instruction:
            config.system_instruction = system_instruction
        if temperature is not None:
            config.temperature = temperature

        try:
            raw_response = await self._client.aio.models.generate_content(
                model=selected_model,
                contents=prompt,
                config=config,
            )
            if hasattr(raw_response, "parsed") and raw_response.parsed is not None:
                if isinstance(raw_response.parsed, response_schema):
                    return raw_response.parsed
                return response_schema.model_validate(raw_response.parsed)
            if raw_response.text:
                return response_schema.model_validate_json(raw_response.text)
            raise GenAIModelError("Model returned empty text or unparseable structured output.")
        except Exception as e:
            logger.error(
                "Error during async structured generation with model %s: %s", selected_model, str(e)
            )
            raise GenAIModelError(f"Async structured GenAI generation failed: {e}") from e

    def _format_response(self, raw_response: Any, model: str) -> AIResponse:
        """Extract application-level AIResponse from raw SDK response."""
        text = raw_response.text or ""
        finish_reason = None
        usage_dict = None

        if hasattr(raw_response, "candidates") and raw_response.candidates:
            first = raw_response.candidates[0]
            if hasattr(first, "finish_reason"):
                finish_reason = str(first.finish_reason)

        if hasattr(raw_response, "usage_metadata") and raw_response.usage_metadata:
            um = raw_response.usage_metadata
            usage_dict = {
                "prompt_token_count": getattr(um, "prompt_token_count", None),
                "candidates_token_count": getattr(um, "candidates_token_count", None),
                "total_token_count": getattr(um, "total_token_count", None),
            }

        return AIResponse(
            text=text,
            model=model,
            finish_reason=finish_reason,
            usage=usage_dict,
        )
