"""Central Google GenAI client wrapper abstraction routing through AI Gateway."""

import logging
from typing import Any, Dict, Optional, Type, TypeVar

from google import genai
from pydantic import BaseModel, Field

try:
    from app.core.config import Settings, get_settings
    from app.core.ai.exceptions import GenAIAuthError, GenAIClientError, GenAIModelError
    from app.ai_gateway.gateway import AIGateway
except ImportError:
    from core.config import Settings, get_settings
    from core.ai.exceptions import GenAIAuthError, GenAIClientError, GenAIModelError
    from ai_gateway.gateway import AIGateway

logger = logging.getLogger(__name__)

T = TypeVar("T", bound=BaseModel)


class AIResponse(BaseModel):
    """Typed application-level AI response abstraction."""

    text: str = Field(default="", description="Text response content generated by the model.")
    model: str = Field(..., description="Model identifier used for generation.")
    finish_reason: Optional[str] = Field(default=None, description="Generation finish reason.")
    usage: Optional[Dict[str, Any]] = Field(
        default=None, description="Token usage statistics if available."
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict, description="Additional model response metadata."
    )


class GenAIClient:
    """Reusable Google GenAI Client abstraction delegating to AIGateway."""

    def __init__(
        self,
        settings: Optional[Settings] = None,
        client: Optional[genai.Client] = None,
        gateway: Optional[AIGateway] = None,
    ) -> None:
        """Initialize GenAIClient.

        Args:
            settings: Settings instance. Defaults to get_settings().
            client: Optional pre-configured genai.Client instance.
            gateway: Optional pre-configured AIGateway instance.
        """
        self._settings = settings or get_settings()
        self._default_model = self._settings.gemini_model

        if gateway is not None:
            self._gateway = gateway
            self._client = gateway.client
        else:
            if client is not None:
                self._client = client
            else:
                try:
                    api_key = self._settings.api_key
                    self._client = genai.Client(api_key=api_key)
                except Exception as e:
                    logger.error("Failed to initialize GenAI client: %s", str(e))
                    raise GenAIAuthError(f"Failed to initialize GenAI client: {e}") from e

            self._gateway = AIGateway(
                settings=self._settings,
                client=self._client,
                backoff_factor=0.01,
            )

    @property
    def default_model(self) -> str:
        """Get default model name."""
        return self._default_model

    @property
    def gateway(self) -> AIGateway:
        """Get underlying AI Gateway instance."""
        return self._gateway

    def generate_text(
        self,
        prompt: str,
        system_instruction: Optional[str] = None,
        model: Optional[str] = None,
        temperature: Optional[float] = None,
    ) -> AIResponse:
        """Generate text response using Gemini model synchronously through AI Gateway."""
        try:
            gw_resp = self._gateway.generate_text(
                prompt=prompt,
                system_instruction=system_instruction,
                model=model,
                temperature=temperature,
            )
            return AIResponse(
                text=str(gw_resp.data),
                model=gw_resp.model,
                finish_reason=gw_resp.finish_reason,
                usage={
                    "prompt_token_count": gw_resp.usage.prompt_tokens,
                    "candidates_token_count": gw_resp.usage.candidate_tokens,
                    "total_token_count": gw_resp.usage.total_tokens,
                },
            )
        except Exception as e:
            selected_model = model or self._default_model
            logger.error("Error during text generation with model %s: %s", selected_model, str(e))
            raise GenAIModelError(f"GenAI generation failed: {e}") from e

    async def generate_text_async(
        self,
        prompt: str,
        system_instruction: Optional[str] = None,
        model: Optional[str] = None,
        temperature: Optional[float] = None,
    ) -> AIResponse:
        """Generate text response using Gemini model asynchronously through AI Gateway."""
        try:
            gw_resp = await self._gateway.generate_text_async(
                prompt=prompt,
                system_instruction=system_instruction,
                model=model,
                temperature=temperature,
            )
            return AIResponse(
                text=str(gw_resp.data),
                model=gw_resp.model,
                finish_reason=gw_resp.finish_reason,
                usage={
                    "prompt_token_count": gw_resp.usage.prompt_tokens,
                    "candidates_token_count": gw_resp.usage.candidate_tokens,
                    "total_token_count": gw_resp.usage.total_tokens,
                },
            )
        except Exception as e:
            selected_model = model or self._default_model
            logger.error("Error during async text generation with model %s: %s", selected_model, str(e))
            raise GenAIModelError(f"Async GenAI generation failed: {e}") from e

    def generate_structured(
        self,
        prompt: str,
        response_schema: Type[T],
        system_instruction: Optional[str] = None,
        model: Optional[str] = None,
        temperature: Optional[float] = None,
    ) -> T:
        """Generate structured response matching a Pydantic model schema synchronously through AI Gateway."""
        try:
            return self._gateway.generate_structured(
                prompt=prompt,
                response_schema=response_schema,
                system_instruction=system_instruction,
                model=model,
                temperature=temperature,
            )
        except Exception as e:
            selected_model = model or self._default_model
            logger.error("Error during structured generation with model %s: %s", selected_model, str(e))
            raise GenAIModelError(f"Structured GenAI generation failed: {e}") from e

    async def generate_structured_async(
        self,
        prompt: str,
        response_schema: Type[T],
        system_instruction: Optional[str] = None,
        model: Optional[str] = None,
        temperature: Optional[float] = None,
    ) -> T:
        """Generate structured response matching a Pydantic model schema asynchronously through AI Gateway."""
        try:
            return await self._gateway.generate_structured_async(
                prompt=prompt,
                response_schema=response_schema,
                system_instruction=system_instruction,
                model=model,
                temperature=temperature,
            )
        except Exception as e:
            selected_model = model or self._default_model
            logger.error("Error during async structured generation with model %s: %s", selected_model, str(e))
            raise GenAIModelError(f"Async structured GenAI generation failed: {e}") from e
